// <auto-generated />
using System;
using ACME_MOTORS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ACME_MOTORS.Migrations
{
    [DbContext(typeof(AcmeMotorContext))]
    [Migration("20190717190749_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ACME_MOTORS.Models.CarModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AmendedOn");

                    b.Property<string>("Color");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EngineId");

                    b.Property<bool>("HasRustDamage");

                    b.Property<string>("ManufacturerId");

                    b.Property<string>("Model");

                    b.Property<int>("QuantityInStock");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.ToTable("cars");
                });

            modelBuilder.Entity("ACME_MOTORS.Models.EngineModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AmendedOn");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("FuelType");

                    b.Property<Guid>("ManufacturerId");

                    b.Property<int>("Mileage");

                    b.Property<string>("Model");

                    b.Property<int>("Size");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.ToTable("engines");
                });

            modelBuilder.Entity("ACME_MOTORS.Models.ManufacturerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AmendedOn");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("manufacturers");
                });

            modelBuilder.Entity("ACME_MOTORS.Models.MotorbikeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AmendedOn");

                    b.Property<string>("Color");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EngineId");

                    b.Property<bool>("HasWindVisor");

                    b.Property<string>("ManufacturerId");

                    b.Property<string>("Model");

                    b.Property<int>("QuantityInStock");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.ToTable("motorbikes");
                });

            modelBuilder.Entity("ACME_MOTORS.Models.TruckModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AmendedOn");

                    b.Property<string>("Color");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EngineId");

                    b.Property<string>("ManufacturerId");

                    b.Property<int>("MaximumLoad");

                    b.Property<string>("Model");

                    b.Property<string>("NumberOfWheels");

                    b.Property<int>("QuantityInStock");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.ToTable("trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
